# Project information
site_name: AAU HPC
site_author: CLAAUDIA, ITS, Aalborg University
site_description: The AAU HPC pages offers comprehensive information on high-performance computing infrastructure, tools, and support available to students and researchers at Aalborg University, helping them maximize their computational capabilities for academic and research purposes.
copyright: Copyright &copy; 2024 CLAAUDIA

nav:
  - Home:
      - Home: index.md
      - Service windows: service-windows.md
      - Tools:
          - HPC Decision Tree: hpc-decision-tree.md
          - HPC Comparison Table: hpc-comparison-table.md
          - Other research softwares: https://www.researcher.aau.dk/guides/research-data-and-software/software-and-tools
        #- HPC Cost Estimator: hpc-cost-estimator.md
  - Strato:
      - About Strato: strato/index.md
      - How to access: strato/how-to-access.md
      - Terms and Conditions: strato/terms-and-conditions.md
      - Usage Management: strato/usage-management.md
      - Guides:
          - Getting started:
              - Before you begin: strato/getting-started/index.md
              - Launch instance: strato/getting-started/launch-instance.md
              - Access instance: strato/getting-started/access-instance.md
              - Transfer files: strato/getting-started/transfer-files.md
              - Shutting down: strato/getting-started/shutting-down.md
          - Application guides:
              - Strato applications: strato/application-guides/strato-applications.md
              - Matlab: strato/application-guides/matlab.md
              - Jupyter Notebook: strato/application-guides/jupyter-notebook.md
              - Docker: strato/application-guides/docker.md
          - Advanced guides:
              - Command line interface access: strato/advanced-guides/command-line-interface-access.md
              - Custom security groups: strato/advanced-guides/custom-security-groups.md
              - Attaching a volume for additional storage: strato/advanced-guides/attaching-a-volume-for-additional-storage.md
              - Persistent terminal sessions: strato/advanced-guides/persistent-terminal-sessions.md
              - Transfer volumes on Strato: strato/advanced-guides/transfer-volume.md
              - Check ownership of instances and volumes on Strato: strato/advanced-guides/check-ownership-guide.md
          - Best-practice guides:
              - Delete and restart an instance from the volume: strato/best-practice-guides/delete-and-restart-an-instance-from-the-volume.md
              - Stop, pause & delete instances: strato/best-practice-guides/stop-pause-and-delete-instances.md
              - Create smaller volumes: strato/best-practice-guides/create-smaller-volumes.md
              - How to Minimize the Risk of Malware: strato/best-practice-guides/how-to-minimize-the-risk-of-malware.md
              - Resize your server: strato/best-practice-guides/resize-your-server.md

  - UCloud:
      - About UCloud: ucloud/index.md
      - How to access: ucloud/how-to-access.md
      - Terms and Conditions: ucloud/terms-and-conditions.md
      - External collaborators: ucloud/external-collaborator.md
      - Providers: ucloud/providers.md
      - Guides:
          - Getting started:
              - Before you begin: ucloud/guides/getting-started/before-you-begin.md
              - File transfer: ucloud/guides/getting-started/transfer-files.md
              - License Management: ucloud/guides/getting-started/Licens.md
          - Guidelines for handling sensitive data: ucloud/guides/sensitive-data-on-ucloud.md
          - Application guides:
              - ChatUI: ucloud/guides/application-guides/ChatUI/index.md
              - Transcriber: ucloud/guides/application-guides/transcriber/index.md
              - Dictaphone: ucloud/guides/application-guides/Dictaphone.md
              - Voyant Tools: ucloud/guides/application-guides/Voyant-Tools.md
          - Advanced guides:
              - Connect Neo4j to VS Code: ucloud/guides/advanced-guides/connect-neo4j-to-vscode.md
      - Use cases:
          - Voice modification for schizophrenia therapy: ucloud/use-cases/voice-modification-schizophrenia.md

  - AI Cloud:
      - About AI Cloud: ai-cloud/index.md
      - How to access: ai-cloud/how-to-access.md
      - System overview: ai-cloud/system-overview.md
      - Terms and Conditions: ai-cloud/terms-and-conditions.md
      - Fair usage: ai-cloud/fair-usage.md
      - Guides:
          - Getting started:
              - Prerequisites: ai-cloud/getting-started/index.md
              - Log in: ai-cloud/getting-started/login.md
              - Look around: ai-cloud/getting-started/look-around.md
              - File transfer: ai-cloud/getting-started/file-management.md
              - Container images: ai-cloud/getting-started/container-images.md
              - Run jobs: ai-cloud/getting-started/run-jobs.md
          - Additional guides:
              - Additional resources: ai-cloud/additional-guides/additional-resources.md 
              - Using the Linux CLI:
                  - Understanding the Linux CLI: ai-cloud/additional-guides/understanding-linux-cli.md
                  - Edit text files with Nano: ai-cloud/additional-guides/edit-text-files-with-nano.md
                  - Useful commands: ai-cloud/additional-guides/useful-commands.md
              - Directories overview: ai-cloud/additional-guides/directories-overview.md
              - Container guides:
                  - Pulling container images from the internet: ai-cloud/additional-guides/download-container-images.md
                  - Building your own container image: ai-cloud/additional-guides/building-your-own-container-image.md
                  - Creating a virtual environment: ai-cloud/additional-guides/creating-a-virtual-environment.md
                  # - Creating a Conda environment: ai-cloud/additional-guides/creating-a-conda-environment.md
              - Running jobs:
                  - Multiple GPUs with PyTorch: ai-cloud/additional-guides/multiple-gpus-with-pytorch.md
                  - Checkpointing: ai-cloud/additional-guides/checkpointing.md
                  - CPU, GPU, and memory allocation: ai-cloud/additional-guides/cpu-gpu-and-memory-allocation.md
                  - Setting a time limit: ai-cloud/additional-guides/setting-a-time-limit.md
                  - Cancelling jobs: ai-cloud/additional-guides/cancelling-jobs.md
              - Monitoring commands:
                  - Checking the queue: ai-cloud/additional-guides/checking-the-queue.md
                  - Checking the status of compute nodes: ai-cloud/additional-guides/checking-the-status-of-compute-nodes.md
                  - Checking GPU utilisation: ai-cloud/additional-guides/checking-gpu-utilisation.md
              - Application examples:
                  - Batch LLM Inference: ai-cloud/additional-guides/batch-llm-inference.md

  - AI-LAB:
      - About AI-LAB: ai-lab/index.md
      - How to access: ai-lab/how-to-access.md
      - System overview: ai-lab/system-overview.md
      - Troubleshooting: ai-lab/troubleshooting.md
      - Terms and Conditions: assets/terms-and-conditions-ai-lab.pdf
      - Fair Usage: ai-lab/fair-usage.md
      - Guides:
          - Index: ai-lab/guides/index.md
          - Video Onboarding Guide: ai-lab/guides/video-onboarding-guide.md
          - Getting started:
              - 1. Prerequisites: ai-lab/guides/prerequisites.md
              - 2. Login: ai-lab/guides/login.md
              - 3. File Handling: ai-lab/guides/file-handling.md
              - 4. Running Jobs: ai-lab/guides/running-jobs.md
              - 5. Getting Containers: ai-lab/guides/getting-containers.md
              - 6. Using Containers: ai-lab/guides/using-containers.md
              - 7. Monitoring: ai-lab/guides/monitoring.md
          - Additional Guides:
              - Batch LLM Inference: ai-lab/guides/batch-llm-inference.md
              - Checkpointing: ai-lab/guides/checkpointing.md
              - Requeuing jobs: ai-lab/guides/requeuing-jobs.md
              - CI/CD with GitHub Actions: ai-lab/guides/ci-cd-with-github-actions.md
          - Workshop:
              - 1. Introduction to AI-LAB: ai-lab/workshop/1-Introduction-to-ai-lab.md
              - 2. What is AI-LAB?: ai-lab/workshop/2-what-is-ai-lab.md
              - 3. AI-LAB Under the Hood: ai-lab/workshop/3-ai-lab-under-the-hood.md
              - 4. The AI-LAB Workflow: ai-lab/workshop/4-the-ai-lab-workflow.md
              - 5. Logging into AI-LAB: ai-lab/workshop/5-logging-into-ai-lab.md
              - 6. File Handling on AI-LAB: ai-lab/workshop/6-file-handling-on-ai-lab.md
              - 7. Essential Linux Commands: ai-lab/workshop/7-essential-linux-commands.md
              - 8. Transferring Files: ai-lab/workshop/8-transferring-files.md
              - 9. Slurm: ai-lab/workshop/9-slurm.md
              - 10. Two Ways of Running Jobs: ai-lab/workshop/10-two-ways-of-running-jobs.md
              - 11. Exercise 1: ai-lab/workshop/11-exercise-1.md
              - 12. Creating a job script: ai-lab/workshop/12-creating-a-sbatch-script.md
              - 13. Exercise 2: ai-lab/workshop/13-exercise-2.md
              - 14. Allocating Resources: ai-lab/workshop/14-allocating-resources.md
              - 15. Containers: ai-lab/workshop/15-containers.md
              - 16. Getting Containers: ai-lab/workshop/16-getting-containers.md
              - 17. Using Containers: ai-lab/workshop/17-using-containers.md
              - 18. Exercise 3: ai-lab/workshop/18-exercise-3.md
              - 19. Final pointers: ai-lab/workshop/19-final-pointers.md

  - TAAURUS:
      - About TAAURUS: taaurus/index.md
      - Applying for a TAAURUS project: taaurus/guides/applying-for-a-taaurus-project.md
      - System overview: taaurus/system-overview.md
      - Terms and Conditions: https://serviceportal.aau.dk/now/nav/ui/classic/params/target/kb_view.do%3Fsys_kb_id%3D7de0759b83783650e1c9f665eeaad396%26sysparm_rank%3D2%26sysparm_tsqueryId%3D09f45a0d8355f290e1c9f665eeaad392
      - Guides:
          - How to log in: taaurus/guides/login.md
          - Navigating TAAURUS: taaurus/guides/navigating-taaurus.md
          - Import & export of data: taaurus/guides/import-export-of-data.md
          - Run GPU jobs:
              - Before running jobs: taaurus/guides/before-running-jobs.md
              - Running Jobs: taaurus/guides/running-jobs.md
              - Getting Containers: taaurus/guides/getting-containers.md
              - Using Containers: taaurus/guides/using-containers.md
              - Monitoring: taaurus/guides/monitoring.md

  - External HPC:
      - External HPC facilities: external-hpc/index.md
      - DeiC HPC resources: external-hpc/deic-resources.md
      - EuroHPC resources: external-hpc/eurohpc-resources.md
      - LUMI: external-hpc/lumi.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.annotate
    - navigation.sections
    - toc.integrate
    - navigation.external_links

  logo: assets/img/aau-logo-512x512.png
  favicon: assets/favicon.ico

  font:
    text: barlow

  language: en

  icon:
    annotation: material/plus-circle

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/conditional.js
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
  - javascripts/mermaid-init.js

markdown_extensions:
  - footnotes
  - toc:
      toc_depth: 2
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.caret
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

validation:
  omitted_files: ignore
  absolute_links: ignore
  unrecognized_links: ignore

extra:
  generator: false
  social:
    - icon: fontawesome/solid/message
      link: https://serviceportal.aau.dk/serviceportal?id=emp_taxonomy_topic&topic_id=82a253e8838fc21053711d447daad328

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/claaudia/

    - icon: fontawesome/solid/globe
      link: https://www.researcher.aau.dk/contact/claaudia

extra_watch:
  - docs/overrides/home.html
  - docs/overrides/hpc-decision-tree.html
